### ISSUE TITLE
Choose a Project License 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/influence-texas#32]
Via @AmyMosley 

> which type of open “license” should we select? (see Open Leaders etherpad/slide deck)

**Comment by mscarey** [comment]
Since Hack for Change, we've had The Unlicense. It's not a license I'd heard of before, but it's on Github's license menu, and it looks like it's similar to the MIT license (very permissive) except it doesn't even require a license and copyright notice. Unlicense is also similar to a CC0 public domain notice.
