### ISSUE TITLE
Define Process for Using campaign database

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/influence-texas#34]
We need to explain/define a process for using campaign database.  

Questions here: 

- Do we need to download parts of it to our own server? If so, when? If so, how much?
- What do you need from the database to get the data science portion of this project up and running? Do we have access to the stuff you need? (yes or no?)
- How much downloading of database info will be needed to accomplish tasks at Civic Hack Sat. Oct. 7?
- Can you come up with tasks that people can help with on that Saturday alone (if not into the future)?
-

**Comment by lazarus1331** [comment]
This is a huge blocker for most developers.

**Comment by lazarus1331** [comment]
Influence Texas PBC will be creating an API that will provide access to this information without the overhead currently necessary to access the TPJ data directly.  This will allow the open source application to consume this information easily and to allow further progress on this by everyone.
We will need to wait until the API is available though, so I'm closing this for now, since the original request was to allow access to TPJ, which will not happen.
